### ISSUE TITLE
Minor modifications

### ISSUE THREAD

**Issue by h-sh-h** [iKintosh/GaborNet#1]
Hello,
Thank you @iKintosh for providing your code.
I'm currently trying to use your layer in my code (with torch 1.1.0) and I ran into some minor problems

I think the following lines should be updated in your code but I'm not sure so I decided to just point them out here :

1- Line 19 -> `padding_mode` should be added 
```
super(GaborSmallConv2d, self).__init__(in_channels, out_channels, kernel_size, stride, padding, dilation, False, _pair(0), groups, bias, padding_mode='zeros')
```
2- Line 24 -> `.type(torch.Tensor)` should be added to make learnable parameter floating
```
self.theta = nn.Parameter(0.628*torch.randint(0, 6, (out_channels, in_channels)).type(torch.Tensor))
```
3- Line 62 -> same as #1
```
super(GaborConv2d, self).__init__(in_channels, out_channels, kernel_size, stride, padding, dilation, False, _pair(0), groups, bias, padding_mode='zeros')
```
4- Line 72 -> second parameter for meshgrid should be `self.x0-1` not `self.x0` (??)
```
y, x = torch.meshgrid([torch.linspace(-self.x0+1, self.x0, self.kernel_size[0]), torch.linspace(-self.y0+1, self.y0, self.kernel_size[1])])
```
5- Line 105 -> same as #1
```
super(GaborCurvedConv2d, self).__init__(in_channels, out_channels, kernel_size, stride, padding, dilation, False, _pair(0), groups, bias, padding_mode='zeros')
```

**Comment by iKintosh** [comment]
Thank you. You're right. 

**1,3,5 makes Gabor Layers not compatible with pytorch 1.1.0 right now.** 

2 -- need to see if it's true, due to the fact that I multiply it by 0.628 it may be float already.
4 -- yes, I'm sure. Python does not include last index in arrays.

**Comment by iKintosh** [comment]
Resolved issue by adding `GaborLayer_1_1_0.py` file, which is compatible with Pytorch 1.1.0.
Old file is now called `GaborLayer_1_0_0.py` and is compatible with Pytorch <=0.4.0, >=1.0.0

https://github.com/iKintosh/GaborNet/blob/f5ce32c8be5e48586041ff869256a0de4610750d/GaborLayers_1_1_0.py#L55-L56

**Comment by iKintosh** [comment]
In addition, turns out that #2 is not an issue. `self.theta` is float.

![image](https://user-images.githubusercontent.com/25372584/62451358-cd4e5e80-b776-11e9-914a-c298ad3c4ea3.png)
