### ISSUE TITLE
Difference between layers

### ISSUE THREAD

**Issue by h-sh-h** [iKintosh/GaborNet#3]
Hello,
Could you please tell me what is the difference between "GaborSmallConv2d", "GaborConv2d" and "GaborCurvedConv2d"? from the math point of view.

**Comment by iKintosh** [comment]
Hi. Sorry for the delay. 
I updated repo: created package and added usage guide!
Also I complitely removed  **GaborSmallConv2d** and **GaborCurvedConv2d** due to the fact that their expediency has not been proven in the article.
